import { useEffect, useState } from "react";
import { ArrowDown, ArrowRight, BookOpen, Flame, MapPin, MoonStar, ShieldCheck, ShoppingBag, Sparkles, Star } from "lucide-react";
import { Link } from "react-router-dom";
import { api } from "../../lib/api";
import { getExpertImage } from "../../lib/media";
import { CinematicSection } from "./CinematicSection";
import { JourneyProvider, useJourney } from "./JourneyProvider";
import { SceneErrorBoundary } from "./SceneErrorBoundary";
import "./cinematic.css";

const stars = Array.from({ length: 42 }, (_, index) => index);
const embers = Array.from({ length: 30 }, (_, index) => index);
const SceneChrome = ({ chapter, eyebrow }) => <><p className="journey-chapter">{chapter}</p><p className="cinematic-kicker"><Sparkles aria-hidden="true" /> {eyebrow}</p></>;

function HeroScene() { const { progress, capability } = useJourney(); const p = capability === "static" ? .62 : progress.home || 0; return <CinematicSection id="home" label="दिव्य यात्रा" className="journey-scene journey-scene--hero"><div className="journey-stage" style={{ "--p": p }}><div className="journey-aura" aria-hidden="true"><i /><i /><i /></div><img className="journey-pandit journey-pandit--hero" src="/cinematic/digipandit-hero.png" alt="" width="1672" height="939" fetchpriority="high" /><div className="journey-copy journey-copy--left"><SceneChrome chapter="01 — आरंभ" eyebrow="DigiPandit Journey" /><h1 id="home-heading">एक मार्गदर्शक।<br /><span>आपकी पूरी आध्यात्मिक यात्रा।</span></h1><p>विश्वसनीय पंडित खोजने से लेकर ज्योतिष, हवन मार्गदर्शन और पूजा सामग्री तक—एक सहज डिजिटल अनुभव।</p><div className="cinematic-actions"><Link className="cinematic-cta cinematic-cta--gold" to="/pandits">पंडित खोजें <ArrowRight /></Link><a className="cinematic-cta cinematic-cta--glass" href="#astrology">यात्रा देखें</a></div><p className="gateway-assurance"><ShieldCheck /> स्पष्ट जानकारी · सुरक्षित अगला कदम</p></div><a className="journey-scroll-cue" href="#pandit-discovery"><span>स्क्रॉल करें</span><ArrowDown /></a></div></CinematicSection>; }

function PanditCard({ pandit, index }) { const name = pandit.user?.name || "पंडित प्रोफ़ाइल"; return <article className="discovery-card" style={{ "--card-index": index }}><img src={getExpertImage(pandit)} alt={name} width="480" height="360" loading="lazy" /><div className="discovery-card__body"><p className="discovery-card__meta"><MapPin /> {pandit.serviceCities?.join(", ") || "सेवा क्षेत्र प्रोफ़ाइल में देखें"}</p><h3>{name}</h3>{typeof pandit.ratingAverage === "number" ? <p className="discovery-rating"><Star /> {pandit.ratingAverage.toFixed(1)}</p> : null}<Link to={`/pandits/${pandit._id}`}>प्रोफ़ाइल देखें <ArrowRight /></Link></div></article>; }

function DiscoveryScene() { const { progress, capability } = useJourney(); const p = capability === "static" ? .68 : progress["pandit-discovery"] || 0; const [state, setState] = useState({ status: "loading", pandits: [] }); useEffect(() => { const controller = new AbortController(); api.get("/pandits", { params: { category: "PUJA", limit: 3 }, signal: controller.signal }).then((response) => { const data = Array.isArray(response.data.data) ? response.data.data : []; setState({ status: data.length ? "success" : "empty", pandits: data }); }).catch((error) => { if (error.code !== "ERR_CANCELED") setState({ status: "error", pandits: [] }); }); return () => controller.abort(); }, []); return <CinematicSection id="pandit-discovery" label="पंडित खोज" className="journey-scene journey-scene--discovery"><div className="journey-stage" style={{ "--p": p }}><div className="journey-location" aria-hidden="true"><span /><i /><b /></div><img className="journey-pandit journey-pandit--discovery" src="/cinematic/digipandit-guide.webp" alt="" width="2048" height="1433" loading="eager" /><div className="journey-copy journey-copy--left"><SceneChrome chapter="02 — पंडित खोज" eyebrow="Verified Guidance" /><h2 id="pandit-discovery-heading">सही स्थान।<br /><span>सही मार्गदर्शक।</span></h2><p>सेवा और स्थान के अनुसार उपलब्ध वास्तविक प्रोफ़ाइल देखें और अपनी आवश्यकता के लिए सही पंडित चुनें।</p><Link className="cinematic-cta cinematic-cta--gold" to="/pandits">सभी पंडित देखें <ArrowRight /></Link></div><div className={`discovery-results discovery-results--${state.status}`}>{state.status === "success" ? state.pandits.map((pandit, index) => <PanditCard key={pandit._id} pandit={pandit} index={index} />) : state.status === "loading" ? [0,1,2].map(i => <div className="discovery-skeleton" key={i}><span /><i /><i /></div>) : <div className="discovery-message"><h3>{state.status === "error" ? "प्रोफ़ाइल अभी लोड नहीं हो सकीं" : "अभी कोई प्रोफ़ाइल उपलब्ध नहीं है"}</h3><Link to="/pandits">पूरी सूची खोलें</Link></div>}</div></div></CinematicSection>; }

function AstrologyScene() { const { progress, capability } = useJourney(); const p = capability === "static" ? .58 : progress.astrology || 0; return <CinematicSection id="astrology" label="ज्योतिष" className="journey-scene journey-scene--astrology"><div className="journey-stage" style={{ "--p": p }}><div className="cosmic-stars" aria-hidden="true">{stars.map(i => <i key={i} style={{ "--i": i }} />)}</div><div className="zodiac-rings" aria-hidden="true"><i /><i /><i /></div><img className="journey-astrologer" src="/cinematic/digipandit-astrologer.png" alt="" width="1672" height="939" loading="lazy" /><div className="journey-copy journey-copy--left"><SceneChrome chapter="03 — ज्योतिष" eyebrow="Cosmic Insight" /><h2 id="astrology-heading">वही मार्गदर्शक।<br /><span>अब तारों की भाषा में।</span></h2><p>दैनिक राशिफल, कुंडली, मिलान और अंक ज्योतिष—आपके मौजूदा DigiPandit tools तक सीधा रास्ता।</p><Link className="cinematic-cta cinematic-cta--gold" to="/astrology">ज्योतिष खोलें <MoonStar /></Link></div></div></CinematicSection>; }

function HawanScene() { const { progress, capability } = useJourney(); const p = capability === "static" ? .64 : progress["hawan-guide"] || 0; return <CinematicSection id="hawan-guide" label="हवन गाइड" className="journey-scene journey-scene--hawan"><div className="journey-stage" style={{ "--p": p }}><div className="dissolve-figure" aria-hidden="true" /><div className="ember-field" aria-hidden="true">{embers.map(i => <i key={i} style={{ "--i": i }} />)}</div><div className="hawan-kund" aria-hidden="true"><span /><i /><b /></div><div className="journey-copy journey-copy--right"><SceneChrome chapter="04 — हवन" eyebrow="Sacred Fire" /><h2 id="hawan-guide-heading">ज्ञान से अग्नि तक।<br /><span>हर चरण स्पष्ट।</span></h2><p>मौजूदा प्रमाणित guide content, progress और safety confirmations के साथ हवन प्रक्रिया को समझें।</p><Link className="cinematic-cta cinematic-cta--gold" to="/hawan-guide">हवन गाइड खोलें <Flame /></Link></div></div></CinematicSection>; }

function StoreScene() { const { progress, capability } = useJourney(); const p = capability === "static" ? .7 : progress["puja-store"] || 0; return <CinematicSection id="puja-store" label="पूजा स्टोर" className="journey-scene journey-scene--store"><div className="journey-stage" style={{ "--p": p }}><div className="store-embers" aria-hidden="true">{embers.slice(0,18).map(i => <i key={i} style={{ "--i": i }} />)}</div><div className="store-pedestal" aria-hidden="true"><span>ॐ</span><i /><b /></div><div className="journey-copy journey-copy--left"><SceneChrome chapter="05 — पूजा स्टोर" eyebrow="Curated Essentials" /><h2 id="puja-store-heading">अग्नि की आभा से।<br /><span>पूजा की तैयारी तक।</span></h2><p>उपलब्ध सामग्री, मूल्य और stock की सही जानकारी सीधे मौजूदा store data से देखें।</p><Link className="cinematic-cta cinematic-cta--gold" to="/store">पूजा स्टोर देखें <ShoppingBag /></Link></div><div className="journey-finale"><BookOpen /><span>धर्मः · ज्ञानम् · सेवा</span></div></div></CinematicSection>; }

function Journey() { const { capability, activeSection } = useJourney(); return <main className="cinematic-home cinematic-home--continuous" data-capability={capability} data-active-scene={activeSection}><a className="journey-skip" href="#pandit-discovery">मुख्य यात्रा पर जाएँ</a><HeroScene /><DiscoveryScene /><AstrologyScene /><HawanScene /><StoreScene /></main>; }
export default function CinematicHome() { return <SceneErrorBoundary><JourneyProvider><Journey /></JourneyProvider></SceneErrorBoundary>; }
