const BOOKING_TYPES = {
  PUJA: "PUJA",
  ASTROLOGY_CHAT: "ASTROLOGY_CHAT",
  ASTROLOGY_CALL: "ASTROLOGY_CALL",
};

const BOOKING_STATUS = {
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
  COMPLETED: "COMPLETED",
};

module.exports = { BOOKING_TYPES, BOOKING_STATUS };
