const PAYMENT_ENTITY_TYPES = {
  BOOKING: "BOOKING",
  STORE_ORDER: "STORE_ORDER",
};

const PAYMENT_STATUS = {
  CREATED: "CREATED",
  PAID: "PAID",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED",
};

module.exports = { PAYMENT_ENTITY_TYPES, PAYMENT_STATUS };
